version: '3.8'

services:
  docker-test:
    container_name: docker-test
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3004:3000'
    env_file:
      - .env

