name: CI

on:
  push:
    branches: [ main ]

jobs:
    ssh_connect:
        name: SSH CONNECT
        runs-on: ubuntu-latest
        steps:
        - name: clone
          continue-on-error: true
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              git clone ${{ github.server_url }}/${{ github.repository }}.git ${{ secrets.DIR_TARGET }} -b ${{ github.ref_name }}
            #  git clone ${{ github.repositoryUrl }} -b ${{ github.ref_name }} ${{ secrets.DIR_TARGET }} --bare
        - name: repo_pull
          if: job.steps.clone.status == failure() || job.steps.world.status == failure()
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              cd ${{ secrets.DIR_TARGET }}
              git pull origin ${{ github.ref_name }}
