name: CI

on:
  push:
    branches: [ main ]

jobs:
    ssh_connect:
        name: SSH CONNECT
        runs-on: ubuntu-latest
        steps:
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              mkdir -p ${{ secrets.DIR_TARGET }}
              cd ${{ secrets.DIR_TARGET }}
              echo ${{ github.repositoryUrl }}
              echo ${{ github.repositoryUrl }}
