name: CI

on:
  push:
    branches: [ main ]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: ${{ env.ssh.HOST }}
            username: ${{ env.ssh.USER }}
            password: ${{ env.ssh.PASSOWRD }}
            port: ${{ env.ssh.PORT }}
            script: |
              mkdir batata
