name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Deployment
        # You may pin to the exact commit or the version.
        # uses: wshihadeh/docker-deployment-action@e11d221fc27fa0aca5bdd09b8d17f816c55d6705
        uses: wshihadeh/docker-deployment-action@v2
        with:
          # Remote Docker host ie (user@host)
          remote_docker_host: ${{secrets.DOCKER_SSH_HOST}}
          # Remote Docker SSH public key
          ssh_public_key: ${{secrets.DOCKER_SSH_PUBLIC_KEY}}
          # SSH private key used to connect to the docker host
          ssh_private_key: ${{secrets.DOCKER_SSH_PRIVATE_KEY}}
