name: CI

on:
  push:
    branches: [ main ]

jobs:
    ssh_connect:
        name: SSH CONNECT
        runs-on: ubuntu-latest
        steps:
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              mkdir -p ${{ secrets.DIR_TARGET }}
    cloneRep:
        name: Clone Repository
        runs-on: ubuntu-latest
        needs: ssh_connect
        steps:
        - name: Download repository from github
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              mkdir -p /home/test/${{ github.event.repository.name }}
